[project]
name = "samla-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.11.0",
    "klavis>=1.5.1",
    "python-dotenv>=1.1.1",
]
